version: '3.8'

services:
  strapi:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: orgma-strapi
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./config:/app/config        # ← ИСПОЛЬЗУЙТЕ bind mounts
      - ./src:/app/src              # ← ИСПОЛЬЗУЙТЕ bind mounts
      - ./public:/app/public        # ← ИСПОЛЬЗУЙТЕ bind mounts
      - ./types:/app/types          # ← ИСПОЛЬЗУЙТЕ bind mounts
      - ./scripts:/app/scripts      # ← ИСПОЛЬЗУЙТЕ bind mounts
      - ./data:/app/data            # ← ИСПОЛЬЗУЙТЕ bind mounts
      - strapi-data:/app/.tmp
    depends_on:
      - minio
    networks:
      - orgma-network


  # Если нужно, добавьте MinIO/S3
  minio:
    build:
      context: ./
      dockerfile: Dockerfile.minio
    image: yagofarovvadim/orgma-minio:latest
    container_name: orgma-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_BROWSER_REDIRECT_URL=https://s3.web.orgma.ru
#      - MINIO_SERVER_URL=https://s3.web.orgma.ru
    volumes:
      - minio-data:/data
    restart: unless-stopped
    networks:
      - orgma-network

volumes:
  strapi-data:
    driver: local
  minio-data:
    driver: local

networks:
  orgma-network:
    driver: bridge